# filepath: Aichatbot_React_Node/netlify.toml
[build]
  command = "cd client && npm install && npm run build && cd ../server && npm install" # MODIFIED LINE
  publish = "client/dist"
  functions = "server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200